from enum import Enum
from typing import Optional

class EnglishLevel(Enum):
    A1_MOVERS = "A1 Movers"    # 剑桥少儿英语一级
    A2_FLYERS = "A2 Flyers"    # 剑桥少儿英语二级

# 按级别分类的完整词汇表
VOCABULARY = {
    EnglishLevel.A1_MOVERS: sorted([
        # 一级上册 (237词)
        "a", "afternoon", "alphabet", "and", "ann", "arm", "armchair", "at", "badminton", "bag", 
        "ball", "baseball", "bath", "bathroom", "be", "beach", "bean", "bed", "bedroom", "between",
        "big", "bike", "bird", "black", "blue", "board", "boat", "body", "book", "bounce", "box",
        "boy", "bread", "breakfast", "brother", "cake", "camera", "car", "cat", "child", "children",
        "class", "classroom", "coconut", "colour", "cow", "crocodile", "cross", "dad", "daddy",
        "desk", "dining room", "dirty", "do", "don't", "dog", "door", "drawing", "dress", "duck",
        "ear", "eat", "egg", "eight", "elephant", "english", "eraser", "eye", "face", "family",
        "father", "fish", "five", "foot", "feet", "four", "friend", "giraffe", "girl", "glasses",
        "goat", "good", "good-bye", "green", "hair", "happy", "he", "head", "helicopter", "hello",
        "her", "here", "him", "his", "horse", "house", "how many", "how old", "i", "ice cream",
        "in", "is", "it", "jacket", "jeans", "juice", "jump", "kitchen", "kite", "know", "lamp",
        "lemon", "letter", "line", "live", "living room", "lizard", "long", "look", "lunch",
        "mango", "me", "milk", "mirror", "monkey", "monster", "mother", "motorbike", "mum",
        "mummy", "my", "name", "new", "next to", "night", "nine", "nose", "not", "now", "of",
        "oh", "old", "on", "one", "open", "or", "our", "paint", "pear", "pen", "pencil", "photo",
        "piano", "picture", "plane", "play", "please", "point", "purple", "put", "question",
        "radio", "read", "red", "rice", "room", "ruler", "run", "school", "see", "seven", "she",
        "sheep", "shirt", "shoe", "sister", "sit down", "six", "skirt", "small", "snake", "soccer",
        "sock", "sofa", "some", "song", "sorry", "start", "sun", "supper", "swim", "table",
        "table tennis", "teacher", "ten", "thank you", "the", "their", "them", "then", "they",
        "this", "three", "tiger", "to", "today", "tomato", "toy", "train", "tree", "try",
        "t-shirt", "two", "ugly", "under", "us", "very", "watch", "water", "watermelon", "we",
        "wear", "what", "where", "which", "white", "who", "whose", "window", "with", "word",
        "write", "yellow", "yes", "you", "young", "your",

        # 一级下册 (136词)
        "add", "again", "animal", "answer", "apple", "ask", "baby", "banana", "basketball",
        "beautiful", "behind", "ben", "bill", "birthday", "bookcase", "brown", "burger", "bus",
        "can", "cannot", "can't", "carrot", "catch", "chicken", "clean", "clock", "close",
        "clothes", "computer", "correct", "cupboard", "day", "example", "favourite", "find",
        "fishing", "floor", "flower", "fly", "food", "french fries", "friday", "frog", "game",
        "garden", "give", "go", "grandfather", "grandmother", "grey", "gray", "guitar", "hall",
        "hand", "handbag", "hat", "hippo", "hit", "hobby", "in front of", "kick", "kim", "learn",
        "leg", "lemonade", "lesson", "like", "listen to", "love", "man", "men", "mat", "may",
        "meat", "mouse", "mice", "mouth", "nick", "no", "not", "number", "on", "onion", "or",
        "orange", "page", "part", "pat", "pea", "phone", "pick up", "pineapple", "pink",
        "potato", "ride", "right", "robot", "sad", "sam", "sausage", "say", "sea", "sentence",
        "short", "show", "sing", "sleep", "so", "spell", "spider", "sport", "stop", "story",
        "sue", "sunday", "talk", "television", "tv", "tell", "tennis", "test", "the", "there",
        "these", "throw", "thursday", "tick", "tom", "trousers", "understand", "walk", "wall",
        "want", "well", "woman", "women"
    ],),

    EnglishLevel.A2_FLYERS: sorted([
        # 二级上册 (298词)
        "actor", "actress", "add", "apartment", "apple", "april", "art", "august", "aunt", "back",
        "badminton", "balcony", "balloon", "barbecue", "barn", "baseball", "basketball",
        "bathroom", "bathtub", "bed", "bedroom", "beef", "beside", "big", "bike riding", "black",
        "blue", "board", "book", "bookshelf", "bowling", "bread", "brother", "brown", "building",
        "bulletin board", "businessman", "businesswoman", "cafeteria", "cake", "calculator",
        "calendar", "cambodia", "camping", "candy", "cat", "celebrate", "chair", "chalk",
        "cheese", "chicken", "classroom", "clinic", "clock", "coke", "cold", "cookie", "cough",
        "counter", "cousin", "cow", "crayon", "cupboard", "curly", "cut", "dark", "december",
        "desk", "dining room", "divide", "doctor", "dog", "driveway", "duck", "earache", "egg",
        "eight", "eighteen", "elephant", "elevator", "eleven", "english", "equal", "eraser",
        "farmhouse", "father", "february", "fever", "fifteen", "fire escape", "fire fighter",
        "fire station", "fish", "five", "football", "footstool", "four", "fourteen",
        "french fries", "friday", "funny", "game board", "garage", "gate", "geography", "giraffe",
        "goat", "grandfather", "grandmother", "grapes", "gray", "green", "hair", "hall",
        "hamburger", "handsome", "happy", "headache", "heavy", "hiking", "hippopotamus",
        "history", "horse", "hospital", "hot", "hot-dog", "house", "hurt", "ice skating",
        "ice cream", "in front of", "indonesia", "interesting", "invite", "january", "japan",
        "jogging", "juice", "july", "june", "kangaroo", "kind", "kitchen", "kite flying", "lamp",
        "library", "lion", "listen to", "living room", "lobby", "long", "mailman", "map", "march",
        "mathematics", "may", "microwave", "milk", "monday", "monkey", "mother", "multiply",
        "music", "neat", "new", "nine", "nineteen", "noisy", "noodle", "nosebleed", "notebook",
        "november", "nurse", "october", "office", "on", "one", "orange", "over", "painting",
        "parking lot", "pen", "pencil", "picnic", "pilot", "ping-pong", "pink", "pizza",
        "player", "playground", "play basketball", "play computer games", "play golf",
        "play soccer", "play tennis", "play video", "police officer", "police station", "pretty",
        "rabbit", "reading", "red", "refrigerator", "rhinoceros", "rice", "roller blading",
        "roof", "rooster", "sailing", "sandwich", "saturday", "school", "science", "scissors",
        "scuba diving", "secretary", "september", "seven", "seventeen", "sheep", "shelf",
        "shopping", "short", "shuffle", "sick", "sightseeing", "singapore", "sink", "sister",
        "six", "sixteen", "skate", "skateboarding", "skiing", "small", "smart", "sneezing",
        "snorkeling", "soccer", "social studies", "sofa", "soup", "south korea", "space",
        "sports field", "square", "stamp collecting", "stapler", "stomach-ache", "straight",
        "streamer", "strong", "student", "subtract", "sunday", "swimming", "table", "tall",
        "tape", "tape player", "teacher", "television", "ten", "tennis", "thailand",
        "the philippines", "theater", "thick", "thin", "thirteen", "thirty", "three",
        "throw the dice", "thursday", "tiger", "toilet", "toothache", "tuesday", "twelve",
        "twenty", "two", "ugly", "uncle", "under", "video", "video player", "vietnam",
        "volleyball", "wardrobe", "waste paper basket", "watch movies", "wednesday",
        "white board", "window", "yard", "yellow", "young", "zebra",

        # 二级下册 (222词)
        "about", "above", "afraid", "after", "afternoon", "all", "always", "another", "any",
        "back", "bad", "badly", "bank", "basement", "bat", "bear", "beard", "because", "before",
        "below", "blanket", "blonde", "bottle", "bus station", "but", "buy", "by", "careful",
        "carefully", "carry", "catch", "cd", "cheese", "choose", "cinema", "city", "clean",
        "climb", "cloud", "cloudy", "clown", "coat", "coffee", "come", "comic", "cook", "cry",
        "cup", "daisy", "dance", "daughter", "difference", "different", "difficult", "dolphin",
        "down", "downstairs", "easy", "eighth", "evening", "every", "fair", "famous", "fan",
        "farm", "fat", "field", "fifth", "film", "fine", "first", "floor", "fly", "forest",
        "fourth", "fred", "fruit", "get undressed", "get up", "glass", "granddaughter",
        "grandparent", "grandson", "grass", "help", "holiday", "home", "homework", "hop", "hot",
        "how", "how much", "how often", "hungry", "inside", "island", "jane", "jill", "jim",
        "john", "jungle", "kick", "lake", "last", "laugh", "leaf", "leaves", "lift", "loud",
        "loudly", "market", "mary", "mean", "mine", "mistake", "moon", "more", "morning", "most",
        "mountain", "mouse", "mice", "moustache", "neck", "need", "never", "ninth", "nothing",
        "off", "often", "ok", "only", "opposite", "ours", "out", "outside", "panda", "parent",
        "park", "parrot", "party", "pasta", "paul", "person", "pet", "peter", "pirate", "place",
        "plant", "quick", "quickly", "rain", "rainbow", "river", "road", "rock", "round", "sail",
        "sally", "scarf", "second", "seventh", "shall", "shark", "shop", "shoulder", "shout",
        "shower", "have a shower", "sixth", "skip", "slow", "slowly", "snow", "something", "son",
        "star", "supermarket", "sweater", "take", "take off", "tea", "temperature", "tenth",
        "than", "that", "theirs", "then", "thing", "think", "third", "thirsty", "those", "tired",
        "tooth", "teeth", "toothbrush", "top", "towel", "treasure", "up", "upstairs", "village",
        "wait", "wash", "waterfall", "weak", "weather", "week", "weekend", "wet", "whale",
        "when", "why", "will", "windy", "work", "world", "wrong", "yesterday", "yours", "zoo"
    ]),
}


